version: '3.0'

services:
  main:
    container_name: 'main'
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8000:8000
    command: npm run dev
    depends_on:
      - mongoDB
    restart: always
  mongoDB:
    container_name: 'mongoDB'
    image: mongo:latest
    env_file:
      - .env
    environment:
      - MONGO_DATA /var/lib/mongodb/data
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
    restart: always
